=== Ahmed1891994/APIFrameworkCucumber/src/test/resources/schemas/author_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "AuthorEntity",
  "type": "object",
  "properties": {
    "id": { "type": "integer" },
    "name": { "type": "string" },
    "age": { "type": "integer" },
    "active": { "type": "boolean" },
    "rating": { "type": ["number", "null"] },
    "totalBooks": { "type": ["integer", "null"] },
    "genres": { "type": ["array", "null"], "items": { "type": "string" } },
    "scores": { "type": ["array", "null"], "items": { "type": "integer" } },
    "wealth": { "type": ["number", "null"] },
    "followers": { "type": ["integer", "null"] }
  },
  "required": ["id", "name", "age"]
}

=== Ahmed1891994/APIFrameworkCucumber/created_author.json
[ {
  "id" : 29,
  "name" : "NNgxttX7lZJ3",
  "age" : 45,
  "active" : true,
  "rating" : 4.5,
  "totalBooks" : 3,
  "genres" : [ "Fiction", "Mystery" ],
  "scores" : [ 90, 85, 78 ],
  "wealth" : 100000.5,
  "followers" : 1500
}, {
  "id" : 30,
  "name" : "GXzAQtpVs3",
  "age" : 35,
  "active" : true,
  "rating" : null,
  "totalBooks" : null,
  "genres" : null,
  "scores" : null,
  "wealth" : null,
  "followers" : null
}, {
  "id" : 31,
  "name" : "yc3I55TR",
  "age" : 40,
  "active" : true,
  "rating" : null,
  "totalBooks" : null,
  "genres" : null,
  "scores" : null,
  "wealth" : null,
  "followers" : null
} ]
